# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
